// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBevmZrgVUXfd0gSUxeVttXeuWFohGNmqA',
    appId: '1:274254356089:web:8ad30475697f0c70c13ea8',
    messagingSenderId: '274254356089',
    projectId: 'ztech-1d0e3',
    authDomain: 'ztech-1d0e3.firebaseapp.com',
    storageBucket: 'ztech-1d0e3.appspot.com',
    measurementId: 'G-7YJNLH1EX4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLYfNeixjO4aTY5BdHXbYiCbpcWRe6Vxw',
    appId: '1:274254356089:android:4f6b74a157903a23c13ea8',
    messagingSenderId: '274254356089',
    projectId: 'ztech-1d0e3',
    storageBucket: 'ztech-1d0e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApGrA15D1fRUFgZqyHB-w57dV-CXQnVWM',
    appId: '1:274254356089:ios:aa6e4862e419894fc13ea8',
    messagingSenderId: '274254356089',
    projectId: 'ztech-1d0e3',
    storageBucket: 'ztech-1d0e3.appspot.com',
    iosBundleId: 'com.example.ztechMobileApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApGrA15D1fRUFgZqyHB-w57dV-CXQnVWM',
    appId: '1:274254356089:ios:136b50308025c80dc13ea8',
    messagingSenderId: '274254356089',
    projectId: 'ztech-1d0e3',
    storageBucket: 'ztech-1d0e3.appspot.com',
    iosBundleId: 'com.example.ztechMobileApplication.RunnerTests',
  );
}
